sudo: required
branches:
  except:
  - datasources
  - wiki
services:
  - docker
install:
  - pip install --upgrade --user awscli
before_script:
  - ./backend/bin/getconfig.sh
script:
  - './backend/bin/test-proj.sh -t'
after_success:
  - ./backend/bin/docker-push.sh
